// import global styles
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-[100dvh]">
        <header className="flex p-2 h-32 bg-green-400 text-4xl"><p>Header Section</p></header>
        <div className="flex flex-grow">{children}</div>
       
        <footer><p className="flex p-2 h-32 bg-blue-400 text-4xl">Footer Section</p></footer>
        </body>
    </html>
  )
}
